# Generated by Django 2.1.5 on 2019-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('amman', 'Amman'), ('irbid', 'Irbid'), ('aqaba', 'Aqaba')], max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
