# Generated by Django 2.1.5 on 2019-01-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Catagories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'SubCatagories',
            },
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=120),
        ),
    ]
