# Generated by Django 2.1.5 on 2019-01-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0002_auto_20190124_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobileNo', models.CharField(max_length=14)),
                ('levelskill', models.CharField(choices=[('beginner', 'Beginner'), ('Medium', 'medium'), ('Expert', 'expert')], max_length=120)),
                ('location', models.CharField(choices=[('I travel to my customers', 'I travel to my customers'), ('Customers travel to me', 'Customers travel to me'), ('Remotely', 'Remotely')], max_length=120)),
                ('distance_limit', models.CharField(choices=[('5 minutes away', '5 minutes away'), ('20 minutes away', '20 minutes away'), ('30 minutes away', '30 minutes away')], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meenfee.Category')),
                ('subCategory', models.ManyToManyField(to='meenfee.SubCategory')),
            ],
            options={
                'verbose_name_plural': 'ServiceProviders',
            },
        ),
    ]
