# Generated by Django 2.1.5 on 2019-01-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0004_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeunit', models.CharField(choices=[('1 hour', '1 hour'), ('2 hour', '2 hour'), ('3 hour', '3 hour')], max_length=120)),
            ],
            options={
                'verbose_name_plural': 'SubCatagories',
            },
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='pricing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meenfee.Pricing'),
            preserve_default=False,
        ),
    ]
