# Generated by Django 2.1.5 on 2019-01-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0005_auto_20190124_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='bannerImage',
            field=models.ImageField(default='', height_field='heightField', upload_to='static/', width_field='widthField'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='instant_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='provide_tools',
            field=models.BooleanField(default=True),
        ),
    ]
