# Generated by Django 2.1.5 on 2019-01-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0007_auto_20190124_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='bannerImage',
            field=models.ImageField(height_field='heightField', upload_to='static/admin/img', width_field='widthField'),
        ),
    ]
