# Generated by Django 2.1.5 on 2019-01-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0009_auto_20190124_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='pricing',
            field=models.CharField(choices=[('1 hour', '1 hour'), ('2 hour', '2 hour'), ('3 hour', '3 hour')], max_length=120),
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
