# Generated by Django 2.1.5 on 2019-01-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0010_auto_20190124_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='pricing',
        ),
    ]
