# Generated by Django 2.1.5 on 2019-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0012_userotherinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userotherinfo',
            options={'verbose_name_plural': 'UserOtherInfos'},
        ),
        migrations.AlterField(
            model_name='userotherinfo',
            name='idcard',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Card Number'),
        ),
        migrations.AlterField(
            model_name='userotherinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number'),
        ),
    ]
