# Generated by Django 2.1.5 on 2019-01-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0013_auto_20190127_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotherinfo',
            name='isphvarified',
            field=models.BooleanField(default=False, verbose_name='Is Phone Varified'),
        ),
    ]
