# Generated by Django 2.1.5 on 2019-01-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0014_userotherinfo_isphvarified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userotherinfo',
            options={'verbose_name': 'User Other Info', 'verbose_name_plural': 'User Other Infos'},
        ),
    ]
