# Generated by Django 2.1.5 on 2019-01-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0015_auto_20190127_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotherinfo',
            name='usertype',
            field=models.CharField(choices=[('provider', 'Provider'), ('requester', 'Requester')], default='requester', max_length=20),
            preserve_default=False,
        ),
    ]
