# Generated by Django 2.1.5 on 2019-01-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0016_userotherinfo_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherinfo',
            name='usertype',
            field=models.CharField(blank=True, choices=[('provider', 'Provider'), ('requester', 'Requester')], max_length=20, null=True),
        ),
    ]
