# Generated by Django 2.1.5 on 2019-01-30 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0020_auto_20190129_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livebooking',
            old_name='booking_id',
            new_name='rowbooking_id',
        ),
        migrations.AlterField(
            model_name='rowbooking',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
