# Generated by Django 2.1.5 on 2019-01-31 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meenfee', '0021_auto_20190130_0520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canceledbooking',
            options={'verbose_name_plural': 'Canceled Booking'},
        ),
        migrations.RenameField(
            model_name='rescheduledappointments',
            old_name='confirmed_by_opp',
            new_name='isconfirmed_by_opp',
        ),
        migrations.AddField(
            model_name='rowbooking',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='canceledbooking',
            name='canceled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
