# Generated by Django 2.1.5 on 2019-02-01 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meenfee', '0024_auto_20190201_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isseen_by_opposite', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delieverd', models.DateTimeField(blank=True, null=True)),
                ('isseen_opposite', models.BooleanField(default=False)),
                ('seen_time', models.DateTimeField(blank=True, null=True)),
                ('notification_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_from', to=settings.AUTH_USER_MODEL)),
                ('notification_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Re-Scheduled Appointments',
            },
        ),
    ]
