# Generated by Django 2.1.5 on 2019-02-01 06:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meenfee', '0028_auto_20190201_0541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReScheduledAppointments',
            new_name='ReScheduledAppointment',
        ),
    ]
