# Generated by Django 2.1.5 on 2019-02-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meenfee', '0029_auto_20190201_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowbooking',
            name='isbookingcompleted',
            field=models.BooleanField(default=False),
        ),
    ]
